// Generated by make generate-test-cases

import XCTest
@testable import SVGView

class SVGCustomTests: BaseTestCase {

    override var dir: String {
        return "Custom"
    }

    func testGraph01() {
        compareToReference("graph-01")
    }

    func testViewport01() {
        compareToReference("viewport-01")
    }

    func testViewport02() {
        compareToReference("viewport-02")
    }

}