// Generated by make generate-test-cases

import Testing
@testable import SVGView

struct SVGCustomTests: SVGTestHelper {

    var dir: String {
        "Custom"
    }

    @Test func graph01() throws {
        try compareToReference("graph-01")
    }

    @Test func viewport01() throws {
        try compareToReference("viewport-01")
    }

    @Test func viewport02() throws {
        try compareToReference("viewport-02")
    }

}