name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly-6.4.x-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: swift test --filter CoreGraphicsPolyfillTests

  test-macos:
    name: Test on macOS
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: swift test --enable-test-discovery
