name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: Linux
            runs-on: ubuntu-latest
            container: swift:5.9
          - os: macOS
            runs-on: macos-latest
    
    container: ${{ matrix.container }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Run tests
      run: make test
      